POST ecommerceapiwebapp-daege4dme6bqbsak.uksouth-01.azurewebsites.net/api/product/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="Name"

Cool Headset
--MyBoundary
Content-Disposition: form-data; name="Price"

49.99
--MyBoundary
Content-Disposition: form-data; name="Description"

Noise-cancelling wireless headset.
--MyBoundary
Content-Disposition: form-data; name="Stock"

25
--MyBoundary
Content-Disposition: form-data; name="Image"; filename="cameraImage.jpg"
Content-Type: image/jpeg

< ./images/cameraImage.jpg
--MyBoundary--