POST ecommerceapiwebapp-daege4dme6bqbsak.uksouth-01.azurewebsites.net/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyMDIwOTc2MTMiLCJ1bmlxdWVfbmFtZSI6IlJhbWk1NWN6Iiwicm9sZSI6ImFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDQyMzk2ODcsImV4cCI6MTc0NDI0MzI4NywiaWF0IjoxNzQ0MjM5Njg3LCJpc3MiOiJlY29tbWVyY2UtYXBwIiwiYXVkIjoiZWNvbW1lcmNlLWFwcCJ9.6HR-AD143E4ToPbO_rhCgP2Ol2CJ0eefVJXANcpyK98
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="Name"

Monitor
--MyBoundary
Content-Disposition: form-data; name="Price"

99.99
--MyBoundary
Content-Disposition: form-data; name="Description"

High Quality Monitor
--MyBoundary
Content-Disposition: form-data; name="Stock"

12
--MyBoundary
Content-Disposition: form-data; name="Image"; filename="speakerImage.jpg"
Content-Type: image/jpeg

< ./images/speakerImage.jpg
--MyBoundary--